# Generated by Django 5.1.7 on 2025-05-29 21:08

import recipeapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0004_cat_recs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=recipeapp.models.rec_path),
        ),
    ]
